Implement lists
Razorr1996/dbp-python-learn-challenge pull request #1
Opened 2023-09-02 22:37 UTC by Razorr1996

2023-09-09 20:08 UTC, aleksandr-semenov-dbp requested changes

2023-09-09 20:08 UTC, aleksandr-semenov-dbp commented on lists/lists.py
> +        max_element = max(replace_list)
по условию задания max() использовать нельзя

2023-09-09 23:45 UTC, Razorr1996 commented on lists/lists.py
> +        max_element = max(replace_list)
Manual implemented search max element

2023-09-11 07:04 UTC, aleksandr-semenov-dbp approved these changes

2023-09-11 07:07 UTC, merged