Implement maps
Razorr1996/dbp-python-learn-challenge pull request #2
Opened 2023-09-02 23:10 UTC by Razorr1996

2023-09-09 20:12 UTC, aleksandr-semenov-dbp requested changes

2023-09-09 20:12 UTC, aleksandr-semenov-dbp commented on maps/maps.py
> +            and len(MapExercise.get_movie_countries(m)) >= 2,
в принципе правильно, но в результате получается очень неэффективный подсчет числа стран. Метод split() по сути используется для подсчета запятых, а порождает дополнительные объекты, что в питоне довольно медленно

2023-09-10 09:11 UTC, Razorr1996 commented on maps/maps.py
> +            and len(MapExercise.get_movie_countries(m)) >= 2,
Rewrote with `str.count()`

2023-09-11 07:04 UTC, aleksandr-semenov-dbp approved these changes

2023-09-11 07:07 UTC, merged